# Generated by Django 6.0 on 2025-12-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rattles", "000_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="aadhar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="blood_group",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
